### ISSUE TITLE
VGA gain is limited to 30 dB, but MAX2830 allows for 62 dB. 

### ISSUE THREAD

**Issue by godsic** [rigexpert/gr-rigexpert#2]
According to p. 21 of [MAX2830 datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/MAX2830.pdf) it allows for up to 62 dB of VGA gain (5 bits in Reg. 11). However in https://github.com/rigexpert/gr-rigexpert/blob/a52589b56945ab7865d48dc87d89e9addf354dc0/fobos/fobos.c#L1222 
its value is limited to 30 dB (maximum allowed value in the register is 15 instead of 31). Is it typo or done intentionally?

**Comment by rigexpert** [comment]
Maximum VGA gain is deliberately limited to idx=15, because our MAX2830 has inexplicable behavior on higher gain index. I and Q channels gains are significantly different causing huge IQ imbalance. Datasheets not always provide completely correct information.

**Comment by godsic** [comment]
@rigexpert Fair enough, thanks for the explanation.

**Comment by waterwin** [comment]
The VGA Drop Down list is showing dB values from 0dB to 30 dB in steps of 2 dB, when choosing 30 dB the GNU Source block is showing 15. That is confusing.
