### ISSUE TITLE
Documentation for GPIO pins 

### ISSUE THREAD

**Issue by godsic** [rigexpert/gr-rigexpert#5]
Would you be so kind to document more transparently all those GPIO pins that are used to control LNAs and filters? This would allow prospective contributors to play around with those, for example, to further optimize SINAD.

**Comment by waterwin** [comment]
I do see them in the documentation under Features and in the source code. I do not find any connectivity on the pcb itself ...

**Comment by rigexpert** [comment]
Sorry, but all hardware configuration stuff as well as PCB, LNA and filters are not for public release.
