### ISSUE TITLE
Using the Fobos SDR via usb into a Oracle VirtualBox

### ISSUE THREAD

**Issue by waterwin** [rigexpert/gr-rigexpert#6]
Where my SDRplay RSP1B can be coupled into the VirtualBox Ubuntu machine, my Fobos SDR can not.
What is wrong (?) or at least different with a complete USB implementation for the Fobos SDR.
Can this be related to the use of USB 3.0 ?
It is now not possible to use the GRC setup from a Windows machine.

lsusb
Bus 001 Device 002: ID 1df7:3050 SDRplay 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

Could not find a USB device with uuid {4ea7dd39-775e-41f5-9509-3c3b78f2bd92}
Callee RC:  E_FAIL (0X80004005)

**Comment by godsic** [comment]
I used KVM-based VM with Windows 11. Passthrough the entire USB bridge (requires VTd support on your host CPU side) and SDR# worked flawlessly.

**Comment by waterwin** [comment]
Additional: when starting the usb connection new
Failed to create a proxy device for the USB device. (Error: VERR_PDM_NO_USB_PORTS).</p>

Result Code:  E_FAIL (0X80004005)

Component:  ConsoleWrap
Interface:  IConsole {6ac83d89-6ee7-4e33-8ae6-b257b2e81be8}

**Comment by waterwin** [comment]
I am not sure I understand the KVM setup, KVM is for Linux and can run a Windows VM. I want to go from Windows 10 to a Ubuntu Virtual Machine created in Oracle VirtualBox, Excuse my ignorance.

**Comment by godsic** [comment]
Oh, sorry, misunderstood you. Unfortunately cannot help, because my knowledge of Windows virtualization capabilities is very limited.

**Comment by waterwin** [comment]
_I'll try the Linux subsystem for Windows approach instead. Thanks anyway_

WRONG, my bad, I should have activated xHCI as USB controller in VirtualBox to access via USB 3.0 protocol.
Example with OOT Source block now works ....

**Comment by waterwin** [comment]
Solution : activate xHCI as USB controller in VirtualBox -- so not an issue, user error
